### PR TITLE
Decoupling Splunk + POM Cleanup + Code Climate + Security Vulnerabilities +Rebase of Decoupling IAMP Commons

### PR DESCRIPTION
**Pull request by TayGov**
# Description

Fix all the things 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## For bcgov contributors:

this PR fixes jira ticket: **put the jira ticket # here**

### CODE REVIEW

**Review by alexjoybc — CHANGES_REQUESTED** [review]
Feels like it's too much of a change ;-)

**Review by sdevalapurkar-bcgov — APPROVED** [review]
awesome! missing newlines at end of postman files but just a nit

**Comment by alexjoybc** [comment]
> awesome! missing newlines at end of postman files but just a nit

postman files are autogen, nothing we can do lol

**Review by alexjoybc — APPROVED** [review]
participate in this lol

**Pull request merged**
